imgfiles = {'../data/plasma0001.png', '../data/plasma0005.png', ...
    '../data/plasma0010.png', '../data/plasma0015.png', ...
    '../data/plasma0025.png', '../data/plasma0050.png', ...
    '../data/plasma0075.png', '../data/plasma0100.png', ...
    '../data/plasma0150.png', '../data/plasma0250.png', ...
    '../data/plasma0500.png', '../data/plasma1000.png', ...
    '../data/plasma2500.png', '../data/plasma5000.png', ...
    '../data/plasma7500.png'};

fprintf('File                            Total    Per image Per pixel\n');
for imgname = imgfiles 
    disp(['Loading ' char(imgname)]);
    img = imread(char(imgname));
    img_info = imfinfo(char(imgname));
    img_bit_depth = img_info.BitDepth;
    disp(['Processing ' char(imgname)]);
    [t_total, t_per_image, t_per_pixel] = hist_benchmark(img, img_bit_depth, 16, 20);
    fprintf('%-32s%-9.5f%-10.6f%e\n', char(imgname), t_total, t_per_image, t_per_pixel);
end
